openapi: 3.0.0
info:
  title: gis
  version: 1.0.0
servers:
  - url: https://asia-southeast2-awangga.cloudfunctions.net
components:
  securitySchemes:
    Login:
      type: apiKey
      name: Login
      in: header
paths:
  /logiccoffee/data/roads:
    post:
      tags:
        - default
      summary: Roads
      security:
        - Login: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                long: 107.57568901934862
                lat: -6.87442753267392
                max_distance: 600
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /logiccoffee/data/region:
    post:
      tags:
        - default
      summary: Region
      security:
        - Login: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                long: 107.57568901934862
                lat: -6.87442753267392
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
